import { NotebookEntry } from '@/types';

/**
 * PDF Export — uses browser's native print API instead of jspdf.
 * This avoids the jspdf/fflate SSR build error in Next.js Turbopack entirely.
 * The user clicks "Generate Report", a beautifully styled print dialog opens,
 * and they choose "Save as PDF" — works natively in every browser.
 */
export function exportSourceAsPdf(entry: NotebookEntry, summaryText: string): void {
  const safeSummary = summaryText
    .replace(/#{1,6}\s(.+)/g, '<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/^- (.+)/gm, '<li>$1</li>')
    .replace(/<\/li>\n<li>/g, '</li><li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br/>');

  const trustBadgeColor =
    entry.source.trust_score >= 75 ? '#10b981' :
    entry.source.trust_score >= 50 ? '#3b82f6' :
    entry.source.trust_score >= 25 ? '#f59e0b' : '#ef4444';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>REAVES Report — ${entry.source.title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Inter', Arial, sans-serif;
      font-size: 11pt;
      color: #1e1e2e;
      background: white;
      padding: 20mm 20mm 20mm 20mm;
      line-height: 1.6;
    }
    .header { border-bottom: 3px solid #7c3aed; padding-bottom: 12px; margin-bottom: 20px; }
    .brand { font-size: 10pt; font-weight: 700; color: #7c3aed; letter-spacing: 0.12em; text-transform: uppercase; }
    h1 { font-size: 16pt; font-weight: 700; color: #1e1e2e; margin-top: 8px; line-height: 1.3; }
    .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; margin: 16px 0; background: #f8f8fc; padding: 14px; border-radius: 8px; border: 1px solid #e5e5f0; }
    .meta-item { }
    .meta-label { font-size: 8pt; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: #888; }
    .meta-value { font-size: 10pt; color: #333; font-weight: 500; }
    .trust-badge { display: inline-block; background: ${trustBadgeColor}; color: white; font-weight: 700; font-size: 10pt; padding: 3px 10px; border-radius: 20px; }
    .section { margin-top: 20px; }
    .section-title { font-size: 12pt; font-weight: 700; color: #7c3aed; border-bottom: 1px solid #ede9fe; padding-bottom: 6px; margin-bottom: 12px; }
    .user-note { background: #fefce8; border-left: 4px solid #facc15; padding: 12px 16px; border-radius: 4px; font-style: italic; color: #555; }
    .tag { display: inline-block; background: #ede9fe; color: #6d28d9; font-size: 9pt; font-weight: 600; padding: 2px 10px; border-radius: 20px; margin-bottom: 12px; }
    p { margin-bottom: 10px; }
    h3 { font-size: 11pt; font-weight: 600; color: #333; margin: 14px 0 6px; }
    ul { padding-left: 20px; margin-bottom: 10px; }
    li { margin-bottom: 4px; }
    .footer { margin-top: 28px; padding-top: 10px; border-top: 1px solid #e5e5e5; font-size: 8pt; color: #aaa; display: flex; justify-content: space-between; }
    @media print {
      body { padding: 0; }
      @page { margin: 20mm; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="brand">REAVES Research Report</div>
    <h1>${entry.source.title}</h1>
  </div>

  <div class="meta">
    <div class="meta-item">
      <div class="meta-label">Authors</div>
      <div class="meta-value">${entry.source.authors}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Year</div>
      <div class="meta-value">${entry.source.year}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Journal</div>
      <div class="meta-value">${entry.source.journal}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Trust Score</div>
      <div class="meta-value"><span class="trust-badge">${entry.source.trust_score}/100</span></div>
    </div>
  </div>

  ${entry.tag && entry.tag !== 'Untagged' ? `<span class="tag">${entry.tag}</span>` : ''}

  ${entry.user_note ? `
  <div class="section">
    <div class="section-title">Your Notes</div>
    <div class="user-note">${entry.user_note}</div>
  </div>` : ''}

  <div class="section">
    <div class="section-title">AI Summary</div>
    <p>${safeSummary}</p>
  </div>

  <div class="section">
    <div class="section-title">Trust Assessment</div>
    <p>${entry.source.trust_reason}</p>
  </div>

  <div class="footer">
    <span>Generated by REAVES · ${new Date().toLocaleDateString()}</span>
    ${entry.source.doi ? `<span>DOI: ${entry.source.doi}</span>` : ''}
  </div>

  <script>
    window.addEventListener('load', function() {
      // Small delay to let fonts load
      setTimeout(function() { window.print(); }, 400);
    });
  </script>
</body>
</html>`;

  const printWin = window.open('', '_blank', 'width=800,height=900');
  if (!printWin) {
    alert('Please allow popups for this site to generate the PDF report.');
    return;
  }
  printWin.document.write(html);
  printWin.document.close();
}
